version: '3.8'
services:
  api:
    build: .  # <-- Cambiar esto, ya que la API está en la raíz
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db

  frontend:
    build: ./frontend-prueba  # Esta línea se mantiene igual
    ports:
      - "8080:80"
    depends_on:
      - api

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "contrasenia!Passw0rd"
      ACCEPT_EULA: "Y"
